############################################################################### 
### USAR EXTENSÃO [ Rest Client ] no VS Code! #################################
###############################################################################

@UrlBase = http://localhost:3000

# Fazer cadastro na aplicação
# @name RegistroDeUsuario
POST {{UrlBase}}/users/register
Content-Type: application/json

{
  	"name": "Harry Potter",
	"email": "pottah@ministry.gov.uk",
	"cpf": "11122233319",
	"sexo": "M",
	"phone": "43999210522",
	"birthdate": "1999-12-31",
	"password": "bettercallsaul"
}

###############################################################################
###############################################################################
###############################################################################

# Fazer login na aplicação
# @name LoginDeUsuario

@LoginToken = {{LoginDeUsuario.response.body.$.token}}

POST {{UrlBase}}/users/login
Content-Type: application/json

{
  "username": "11122233319",
  "password": "bettercallsaul"
}

###############################################################################
###############################################################################
###############################################################################

# Retornar usuário atual (logado)
# @name UsuarioAtual

GET {{UrlBase}}/users/@me
Authorization: {{LoginToken}}

###############################################################################
###############################################################################
###############################################################################

# Envia um e-mail de reset de senha
# @name ResetPassword

#@LoginToken = {{LoginDeUsuario.response.body.$.token}}

POST {{UrlBase}}/users/reset/password
#GET {{UrlBase}}/users/reset/password
Content-Type: application/json


###############################################################################
###############################################################################
################################################################################ Cria um plano de aula
# @name CreateClassPlan

#@LoginToken = {{LoginDeUsuario.response.body.$.token}}

POST {{UrlBase}}/plan/create
Content-Type: application/json

{
  "syllabus": "A disciplina apresenta conceitos de análise e projeto orientados a objetos e a Linguagem de modelagem unificada (UML)",
  "content": "Introdução a Análise e Projeto Orientado a Objetos; Casos de Uso; Detalhamento do caso de uso; UML Unified Modeling Language e seus diagramas;  Análise Orientada a Objetos Modelo estático do sistema Modelo dinâmico do sistema3319",
  "classesQuantity": 20
}
###############################################################################
###############################################################################
###############################################################################
